### ISSUE TITLE
waitForElementPresent

### ISSUE THREAD

**Issue by samface** [jlipps/sausage#23]
In my code I have a javascript that adds elements to the DOM and I need a function that waits for the elements to be present. So far I have managed to come up with the following:

<pre>
$test = $this;
$this->waitUntil(function() use ($test) {
  try {
    $boolean = ($test->byId("element-id") instanceof \PHPUnit_Extensions_Selenium2TestCase_Element);
  } catch (\Exception $e) {
    $boolean = false;
  }
  return $boolean === true ?: null;
});
</pre>

However, this gives me the following error:

PHPUnit_Extensions_Selenium2TestCase_WebDriverException: Timed out after 0 seconds

Any idea how I can get this to work?

**Comment by shehi** [comment]
This being rather a browser related issue/defect, shouldn't this issue be closed?
