### ISSUE TITLE
Readme states PHP 5.3+ supported, but unable to get it working in PHP 5.3. Works fine in PHP 5.4

### ISSUE THREAD

**Issue by agileware** [jlipps/sausage#26]
G'day,

Just thought I'd let you know that the readme states PHP 5.3+ is supported. However, I've been unable to get this working. However, it does work fine in PHP 5.4.

Here's the output from PHP 5.3:
[test@centos sauce-tutorial]# vendor/bin/phpunit WebDriverDemo.php
PHP Fatal error:  Uncaught exception 'Exception' with message 'No browsers found.' in /test/sauce-tutorial/vendor/sauce/sausage/src/Sauce/Sausage/WebDriverTestCase.php:243
Stack trace:
#0 /test/sauce-tutorial/vendor/sauce/sausage/src/Sauce/Sausage/WebDriverTestCase.php(17): Sauce\Sausage\WebDriverTestCase::browsers()
#1 [internal function]: Sauce\Sausage\WebDriverTestCase::suite('WebDriverDemo')
#2 /test/sauce-tutorial/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(124): ReflectionMethod->invoke(NULL, 'WebDriverDemo')
#3 /test/sauce-tutorial/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit_Runner_BaseTestRunner->getTest('WebDriverDemo', '/test/sauce-tut...', Array)
#4 /test/sauce-tutorial/vendor/phpunit/phpunit/src/TextUI/Command.php(132): PHPUnit_TextUI_Command->run(Array, true)
#5 /test/sauce-tutorial/vendor/phpunit/phpunit/phpunit(55): PHPUnit_TextUI_Command::main()
#6 {main}
  thrown in /test/sauce-tutorial/vendor/sauce/sausage/src/Sauce/Sausage/WebDriverTestCase.php on line 243

[test@centos sauce-tutorial]# php -v
PHP 5.3.3 (cli) (built: Dec 11 2013 03:29:57)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with the ionCube PHP Loader v4.2.1, Copyright (c) 2002-2012, by ionCube Ltd.

**Comment by emilient** [comment]
I had the same issue; WebDriverTestCase class use a Trait; this feature was introduce in PHP 5.4;
So this library is definitely not compatible with PHP 5.3.

**Comment by jlipps** [comment]
good point. i'll update the readme

**Comment by jlipps** [comment]
it is already in the readme.
