### ISSUE TITLE
SSL Certificate problem with CURL & saucelabs (on travis)

### ISSUE THREAD

**Issue by wgroeneveld** [jlipps/sausage#35]
Hi,

I keep on getting this while running tests in travis:
Exception: Got an error while making a request: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
(no sauce connect needed, don't run them locally, I first deploy to a public server and use that as URL for selenium)

Seems to be related to https://github.com/Codeception/Codeception/issues/1649 - there's a fix posted there which adds CURL options (as could be done in sauceapi.php) to ignore certificate validation, but I'm not sure if that is the real issue or if that is a good idea.

Anyone with similar problems? Full stack:

Exception: Got an error while making a request: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
/home/travis/build/vendor/sauce/sausage/src/Sauce/Sausage/SauceAPI.php:67
/home/travis/build/vendor/sauce/sausage/src/Sauce/Sausage/SauceAPI.php:87
/home/travis/build/vendor/sauce/sausage/src/Sauce/Sausage/SauceTestCommon.php:17
/home/travis/build/vendor/sauce/sausage/src/Sauce/Sausage/SauceTestCommon.php:17
/home/travis/build/vendor/sauce/sausage/src/Sauce/Sausage/TestCase.php:151
phar:///home/travis/.phpenv/versions/5.5.21/bin/phpunit/phpunit/Framework/TestSuite.php:716
phar:///home/travis/.phpenv/versions/5.5.21/bin/phpunit/phpunit/Framework/TestSuite.php:716
phar:///home/travis/.phpenv/versions/5.5.21/bin/phpunit/phpunit/Framework/TestSuite.php:716
phar:///home/travis/.phpenv/versions/5.5.21/bin/phpunit/phpunit/TextUI/TestRunner.php:388
phar:///home/travis/.phpenv/versions/5.5.21/bin/phpunit/phpunit/TextUI/Command.php:151
phar:///home/travis/.phpenv/versions/5.5.21/bin/phpunit/phpunit/TextUI/Command.php:103

Travis config doesn't contain anything unusual, - phpunit tests_acceptance/ as a script and the secure credentials to saucelabs. 

Thanks a bunch!

**Comment by mckracken83** [comment]
Where do I set this environment variable? I'm using CircleCI.

**Comment by jlipps** [comment]
hmm, I'm not sure how to set env vars using CircleCI, that would be a question for the CircleCI folks. but this is fairly common practice so there's probably a way. for travis, for example, you set it in the travis.yml configuration file that lives in your repo.

**Comment by mckracken83** [comment]
ah ok, that's easy enough. wasn't sure if I needed to pass that environment variable to sauce via a command line arg tho?

**Comment by jlipps** [comment]
environment variables are set in the environment, so Sausage will pick them up without you having to do anything else.

**Comment by mckracken83** [comment]
my composer file wasn't set to get the latest version of Sausage from this repo - fixed that. now i've got a new hurdle - I'm getting the following error message:

Exception: Got an error while making a request: GnuTLS recv error (-9): A TLS packet with unexpected length was received.

**Comment by jlipps** [comment]
is this still happening? have you tried outside your corporate net?
