### ISSUE TITLE
Travis-ci / Saucelab tests got this error : GnuTLS recv error (-9)

### ISSUE THREAD

**Issue by emilient** [jlipps/sausage#41]
Not every times, but so many times, I got this error from travis-ci tests : 
Exception: Got an error while making a request: GnuTLS recv error (-9): A TLS packet with unexpected length was received.

Travis see 'Error' as test result and saucelab keep 'complete' as result instead of 'passed' whereas the test was successfull.

My research tells that a lots of services now use TLS instead of SSL with curl; so i tried to add some custom option like this in Sauce/Sausage/SauceAPI.php : 
curl_setopt(\$ch, CURLOPT_SSLVERSION, 3);
or 
curl_setopt(\$ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

But nothing works.
I will create a ticket on saucelab about this; but I'm surprised to be alone with this problem.
You can see the issue here i you want : https://travis-ci.org/emilient/Easy_MultipleDomains/builds/56311207

**Comment by Netsensia** [comment]
I also get this exact same problem. Unfortunately I have not yet found a solution. I have tried setting the SAUCE_VERIFY_CERTS env var to false in .travis.yml but this didn't work for me. What surprises me is that it is inconsistent - sometimes tests pass and sometimes they throw up this error.

**Comment by Netsensia** [comment]
I managed to get all my tests passing on Travis by modifying the SauceAPI.php makeRequest function to retry on failure. I don't like it because I don't know why there are so many failures, but this does solve my immediate problems.

    protected function makeRequest($url, $type="GET", $params=false)
    {
        $attempts = 0;
        
        do {
            $ch = curl_init();
            if($this->verify_certs == false) {
                curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            }
    
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_USERPWD, $this->username.":".$this->access_key);
    
            if ($type == "POST")
                curl_setopt($ch, CURLOPT_POST, 1);
            elseif ($type == "PUT")
                curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
            elseif ($type == "DELETE")
                curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE');
    
            // If user has ca bundle location specified in environment
            // set that same path on php curl connection
            if (getenv('CURL_CA_BUNDLE')) {
                curl_setopt($ch, CURLOPT_CAINFO, getenv('CURL_CA_BUNDLE'));
            }
    
            $headers = array();
            $headers[] = 'Content-Type: text/json';
    
            $data = '';
            if ($params) {
                $data = json_encode($params);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
            }
            $headers[] = 'Content-length:'.strlen($data);
    
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
            $response = curl_exec($ch);
    
            $failed = false;
            if (curl_errno($ch)) {
                $failed = true;
                $error = curl_error($ch);
                curl_close($ch);
            }
            
        } while ($failed && ++$attempts < 10);

        if ($failed) {
            throw new \Exception("Got an error while making a request (tried " . $attempts . " times): ".$error);
        }
        
        curl_close($ch);
        
        return $this->convertResult($response);
    }

**Comment by jlipps** [comment]
we can add this to Sausage however it points more to an issue with the Travis environment (or perhaps PHP's connection code?) than Sausage.

**Comment by Netsensia** [comment]
Yes, I completely agree - the tests all run perfectly when I use Sauce Connect on a local VM, so something in the Travis environment would appear to be the problem.

**Comment by emilient** [comment]
I created the issue to travis... will see
https://github.com/travis-ci/travis-ci/issues/3676

**Comment by jlipps** [comment]
thanks @emilient !
