### ISSUE TITLE
SeleniumRCDemo.php doesn't work

### ISSUE THREAD

**Issue by jaydiablo** [jlipps/sausage#46]
I've been trying to get a SeleniumRC test working with sauce/sausage, but kept seeing this exception:

>exception 'RuntimeException' with message 'Invalid response while accessing the Selenium Server at 'http://ondemand.saucelabs.com:80/selenium-server/driver/': Unknown command'

I thought it was me, but when I try to run the SeleniumRCDemo.php script provided in this lib, I get the exact same message.  Here's the URL that PHP is trying to post to:

>http://ondemand.saucelabs.com:80/selenium-server/driver/

And it seems to be trying to issue the command "getNewBrowserSession", based on the post data I dumped (the "cmd" argument is "getNewBrowserSession").

Has something changed with Sauce OnDemand that would be denying this command?

**Comment by jlipps** [comment]
Hi @jaydiablo I believe Sauce has EOLed Selenium RC support; you'll need to use WebDriver instead.

**Comment by jaydiablo** [comment]
Ah, bummer, I was hoping to be able to use PHPUnit's `runSelenese` command, which throws a "not supported yet" sort of error in web driver.

Is that worthy of a ticket?

**Comment by jlipps** [comment]
Unfortunately given that the selenium project itself deprecated RC (it's decades-old tech at this point) I don't see wisdom in trying to build solutions off of it. You're more than welcome to contact Sauce support and let them know of your use case but I don't think it will change anything.
