### ISSUE TITLE
How to define different sets of browsers?

### ISSUE THREAD

**Issue by line-o** [jlipps/sausage#8]
One set is meant to be used for quick local tests and the other is for running tests on sauce with a much larger set of OS/browser combinations.

Setting environment variables in `phpunit.xml` did not do the trick. Because the $browsers array is defined statically and modifying it in the setUp routine is already to late.

Preferrably, the browser configuration is read from the configuration file like the selenium extension does.

**Comment by jlipps** [comment]
The answer according to @giorgiosironi is that self::browsers can be a `public static function` not just a public static variable. This function needs simply to return an array of browsers.
